/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as GameRouteImport } from './routes/game'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCreditsPersonPerson_idRouteImport } from './routes/api/credits.person.$person_id'
import { Route as ApiCreditsMovieMovie_idRouteImport } from './routes/api/credits.movie.$movie_id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsPersonPerson_idRoute =
  ApiCreditsPersonPerson_idRouteImport.update({
    id: '/api/credits/person/$person_id',
    path: '/api/credits/person/$person_id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCreditsMovieMovie_idRoute = ApiCreditsMovieMovie_idRouteImport.update({
  id: '/api/credits/movie/$movie_id',
  path: '/api/credits/movie/$movie_id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/credits/movie/$movie_id': typeof ApiCreditsMovieMovie_idRoute
  '/api/credits/person/$person_id': typeof ApiCreditsPersonPerson_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/credits/movie/$movie_id': typeof ApiCreditsMovieMovie_idRoute
  '/api/credits/person/$person_id': typeof ApiCreditsPersonPerson_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/credits/movie/$movie_id': typeof ApiCreditsMovieMovie_idRoute
  '/api/credits/person/$person_id': typeof ApiCreditsPersonPerson_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/game'
    | '/signin'
    | '/signup'
    | '/api/auth/$'
    | '/api/credits/movie/$movie_id'
    | '/api/credits/person/$person_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/game'
    | '/signin'
    | '/signup'
    | '/api/auth/$'
    | '/api/credits/movie/$movie_id'
    | '/api/credits/person/$person_id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/game'
    | '/signin'
    | '/signup'
    | '/api/auth/$'
    | '/api/credits/movie/$movie_id'
    | '/api/credits/person/$person_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GameRoute: typeof GameRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCreditsMovieMovie_idRoute: typeof ApiCreditsMovieMovie_idRoute
  ApiCreditsPersonPerson_idRoute: typeof ApiCreditsPersonPerson_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/person/$person_id': {
      id: '/api/credits/person/$person_id'
      path: '/api/credits/person/$person_id'
      fullPath: '/api/credits/person/$person_id'
      preLoaderRoute: typeof ApiCreditsPersonPerson_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/movie/$movie_id': {
      id: '/api/credits/movie/$movie_id'
      path: '/api/credits/movie/$movie_id'
      fullPath: '/api/credits/movie/$movie_id'
      preLoaderRoute: typeof ApiCreditsMovieMovie_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GameRoute: GameRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCreditsMovieMovie_idRoute: ApiCreditsMovieMovie_idRoute,
  ApiCreditsPersonPerson_idRoute: ApiCreditsPersonPerson_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
