/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as ApiGameRouteImport } from './routes/api/game'
import { Route as AuthenticatedGameIndexRouteImport } from './routes/_authenticated/game.index'
import { Route as AuthenticatedGameGame_idRouteImport } from './routes/_authenticated/game.$game_id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCreditsMovieMovie_idRouteImport } from './routes/api/credits.movie.$movie_id'
import { Route as ApiCreditsPersonPerson_idRouteImport } from './routes/api/credits.person.$person_id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiGameRoute = ApiGameRouteImport.update({
  id: '/api/game',
  path: '/api/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGameIndexRoute = AuthenticatedGameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGameGame_idRoute =
  AuthenticatedGameGame_idRouteImport.update({
    id: '/game/$game_id',
    path: '/game/$game_id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsMovieMovie_idRoute = ApiCreditsMovieMovie_idRouteImport.update({
  id: '/api/credits/movie/$movie_id',
  path: '/api/credits/movie/$movie_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsPersonPerson_idRoute =
  ApiCreditsPersonPerson_idRouteImport.update({
    id: '/api/credits/person/$person_id',
    path: '/api/credits/person/$person_id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/api/game': typeof ApiGameRoute
  '/game/$game_id': typeof AuthenticatedGameGame_idRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/': typeof AuthenticatedGameIndexRoute
  '/api/credits/movie/$movie_id': typeof ApiCreditsMovieMovie_idRoute
  '/api/credits/person/$person_id': typeof ApiCreditsPersonPerson_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/api/game': typeof ApiGameRoute
  '/game/$game_id': typeof AuthenticatedGameGame_idRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game': typeof AuthenticatedGameIndexRoute
  '/api/credits/movie/$movie_id': typeof ApiCreditsMovieMovie_idRoute
  '/api/credits/person/$person_id': typeof ApiCreditsPersonPerson_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/api/game': typeof ApiGameRoute
  '/_authenticated/game/$game_id': typeof AuthenticatedGameGame_idRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/game/': typeof AuthenticatedGameIndexRoute
  '/api/credits/movie/$movie_id': typeof ApiCreditsMovieMovie_idRoute
  '/api/credits/person/$person_id': typeof ApiCreditsPersonPerson_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/archive'
    | '/stats'
    | '/api/game'
    | '/game/$game_id'
    | '/api/auth/$'
    | '/game/'
    | '/api/credits/movie/$movie_id'
    | '/api/credits/person/$person_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/archive'
    | '/stats'
    | '/api/game'
    | '/game/$game_id'
    | '/api/auth/$'
    | '/game'
    | '/api/credits/movie/$movie_id'
    | '/api/credits/person/$person_id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signin'
    | '/signup'
    | '/_authenticated/archive'
    | '/_authenticated/stats'
    | '/api/game'
    | '/_authenticated/game/$game_id'
    | '/api/auth/$'
    | '/_authenticated/game/'
    | '/api/credits/movie/$movie_id'
    | '/api/credits/person/$person_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiGameRoute: typeof ApiGameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCreditsMovieMovie_idRoute: typeof ApiCreditsMovieMovie_idRoute
  ApiCreditsPersonPerson_idRoute: typeof ApiCreditsPersonPerson_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/game': {
      id: '/api/game'
      path: '/api/game'
      fullPath: '/api/game'
      preLoaderRoute: typeof ApiGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/game/': {
      id: '/_authenticated/game/'
      path: '/game'
      fullPath: '/game/'
      preLoaderRoute: typeof AuthenticatedGameIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/game/$game_id': {
      id: '/_authenticated/game/$game_id'
      path: '/game/$game_id'
      fullPath: '/game/$game_id'
      preLoaderRoute: typeof AuthenticatedGameGame_idRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/movie/$movie_id': {
      id: '/api/credits/movie/$movie_id'
      path: '/api/credits/movie/$movie_id'
      fullPath: '/api/credits/movie/$movie_id'
      preLoaderRoute: typeof ApiCreditsMovieMovie_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/person/$person_id': {
      id: '/api/credits/person/$person_id'
      path: '/api/credits/person/$person_id'
      fullPath: '/api/credits/person/$person_id'
      preLoaderRoute: typeof ApiCreditsPersonPerson_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedGameGame_idRoute: typeof AuthenticatedGameGame_idRoute
  AuthenticatedGameIndexRoute: typeof AuthenticatedGameIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedGameGame_idRoute: AuthenticatedGameGame_idRoute,
  AuthenticatedGameIndexRoute: AuthenticatedGameIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiGameRoute: ApiGameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCreditsMovieMovie_idRoute: ApiCreditsMovieMovie_idRoute,
  ApiCreditsPersonPerson_idRoute: ApiCreditsPersonPerson_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
