/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCreditsPersonPerson_idRouteImport } from './routes/api/credits.person.$person_id'
import { Route as ApiCreditsMovieMovie_idRouteImport } from './routes/api/credits.movie.$movie_id'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsPersonPerson_idRoute =
  ApiCreditsPersonPerson_idRouteImport.update({
    id: '/api/credits/person/$person_id',
    path: '/api/credits/person/$person_id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCreditsMovieMovie_idRoute = ApiCreditsMovieMovie_idRouteImport.update({
  id: '/api/credits/movie/$movie_id',
  path: '/api/credits/movie/$movie_id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/api/credits/movie/$movie_id': typeof ApiCreditsMovieMovie_idRoute
  '/api/credits/person/$person_id': typeof ApiCreditsPersonPerson_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/api/credits/movie/$movie_id': typeof ApiCreditsMovieMovie_idRoute
  '/api/credits/person/$person_id': typeof ApiCreditsPersonPerson_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/api/credits/movie/$movie_id': typeof ApiCreditsMovieMovie_idRoute
  '/api/credits/person/$person_id': typeof ApiCreditsPersonPerson_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/test'
    | '/api/credits/movie/$movie_id'
    | '/api/credits/person/$person_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/test'
    | '/api/credits/movie/$movie_id'
    | '/api/credits/person/$person_id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/test'
    | '/api/credits/movie/$movie_id'
    | '/api/credits/person/$person_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  TestRoute: typeof TestRoute
  ApiCreditsMovieMovie_idRoute: typeof ApiCreditsMovieMovie_idRoute
  ApiCreditsPersonPerson_idRoute: typeof ApiCreditsPersonPerson_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/person/$person_id': {
      id: '/api/credits/person/$person_id'
      path: '/api/credits/person/$person_id'
      fullPath: '/api/credits/person/$person_id'
      preLoaderRoute: typeof ApiCreditsPersonPerson_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/movie/$movie_id': {
      id: '/api/credits/movie/$movie_id'
      path: '/api/credits/movie/$movie_id'
      fullPath: '/api/credits/movie/$movie_id'
      preLoaderRoute: typeof ApiCreditsMovieMovie_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TestRoute: TestRoute,
  ApiCreditsMovieMovie_idRoute: ApiCreditsMovieMovie_idRoute,
  ApiCreditsPersonPerson_idRoute: ApiCreditsPersonPerson_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
